-- CCN Council Prep Pro — fill in missing explanations
--
-- A subscriber reported several questions showing an empty "Why:" with no
-- explanation text at all — specifically flagged "What is a key intervention
-- for MDRO control?" among others. Investigation found this isn't isolated:
-- 31 of 34 "Both A and B"-style questions across the bank went in with
-- exp = NULL, heavily concentrated in Infection Prevention (CLABSI/VAP/MDRO
-- content), plus a handful in Neurology, Renal & Fluid Balance, ICU
-- Pharmacology, and Obstetric & Neonatal. This fills in every one of them.
-- Run this once in the Supabase SQL Editor.

update public.questions as q
set exp = v.exp
from (values
(2436, 'Defibrillation delivers a high-energy shock through the chest — the paddles/pads can burn the skin, and the force involved (plus any chest compressions given around the shock) can fracture ribs, especially in older or osteoporotic patients. Both complications are recognized risks.'),
(2504, 'In septic shock, corticosteroids like hydrocortisone both dampen the excessive inflammatory response driving the shock state and support adrenal function in patients with critical-illness-related corticosteroid insufficiency. Both roles apply, which is why they''re sometimes added for shock that isn''t responding to fluids and vasopressors alone.'),
(2542, 'Brain herniation compresses the oculomotor nerve, causing a fixed, dilated pupil, and disrupts brainstem motor pathways, causing decerebrate (extensor) posturing. Both are classic, often co-occurring signs of herniation and demand urgent action.'),
(2546, 'Mannitol is an osmotic diuretic that pulls fluid out of brain tissue to lower ICP, while dexamethasone reduces vasogenic (fluid-based) swelling, especially around tumors. Both are used to bring down elevated ICP, just through different mechanisms.'),
(2562, 'CRRT removes fluid continuously, which can cause hypotension if fluid is pulled off faster than it can be replaced from the rest of the body, and the indwelling catheter required for CRRT is a direct entry point for infection. Both are recognized complications of the therapy.'),
(2570, 'Diabetes and hypertension are the two leading causes of chronic kidney disease worldwide — high glucose damages the glomeruli directly over time, and chronically elevated pressure damages the small vessels of the kidney. Both are major, well-established risk factors.'),
(2574, 'As a CRRT circuit starts to clot, resistance to blood flow through the filter rises — this shows up as climbing venous (return) pressure and a more negative arterial (access/draw) pressure as the pump struggles to pull blood through the narrowing circuit. Both changes together are a red flag for clotting.'),
(2576, 'Recovering kidney function shows up in two ways together: urine output climbing back toward normal, and creatinine trending back down as the kidneys clear it from the blood again. Both are tracked to confirm genuine recovery rather than a one-off good reading.'),
(2582, 'Repositioning relieves pressure-related discomfort, and music therapy lowers the perception of pain and anxiety. Both are legitimate non-drug pain-relief strategies used alongside medication in the ICU, not instead of it.'),
(2584, 'Prolonged sedation is one of the strongest risk factors for ICU delirium, and it can also blunt the drive to breathe, causing respiratory depression. Both are well-documented downsides of keeping a patient sedated longer than necessary.'),
(2586, 'A daily "sedation vacation" lets the team see the patient''s true neurological status — are they waking appropriately, oriented, following commands — and it cuts the total sedative exposure that drives delirium. Both benefits are why it''s done every day rather than left continuous.'),
(2591, 'Benzodiazepines are one of the strongest drug-related risk factors for ICU delirium, and older age independently raises delirium risk because of reduced cognitive reserve. Both are established, additive risk factors.'),
(2592, 'Frequent reorientation (time, place, situation) and minimizing noise/light disruption both support the normal sleep-wake cycle and mental clarity that delirium disrupts. Both are core non-drug nursing interventions before reaching for more sedation.'),
(2594, 'Treating pain isn''t only about comfort — unrelieved pain also triggers a harmful physiological stress response (raised heart rate, catecholamine release, higher oxygen demand). Good pain management addresses both the comfort side and the stress-response side.'),
(2595, 'Unrelieved pain activates the sympathetic nervous system, which raises both heart rate (tachycardia) and blood pressure (hypertension). Seeing either — or both — in a patient who can''t reliably self-report pain (e.g. sedated or non-verbal) should prompt a pain reassessment.'),
(2598, 'The longer a central line stays in place, the more opportunity bacteria have to colonize it, and poor hand hygiene during insertion or routine line care directly introduces organisms into the line. Both raise CLABSI risk, which is why line duration and hand hygiene are both tracked closely.'),
(2599, 'Antibiotic stewardship exists to slow the development of drug-resistant organisms by avoiding unnecessary or overly broad antibiotic use, and to make sure each patient actually gets the right drug, dose, and duration for their infection. Both goals work together.'),
(2601, 'Using strict aseptic/sterile technique during line insertion and care, combined with routine dressing changes per unit protocol, both reduce the chance of organisms tracking along the catheter into the bloodstream. Both are standard components of a CLABSI-prevention bundle.'),
(2602, 'MRSA (methicillin-resistant Staphylococcus aureus) and VRE (vancomycin-resistant Enterococcus) are both classic examples of a multidrug-resistant organism (MDRO) — that is literally what the term describes: an organism that has become resistant to multiple classes of antibiotics.'),
(2603, 'The VAP-prevention bundle combines several elements at once — chlorhexidine oral care reduces the bacterial load that could be aspirated into the lungs, and daily sedation interruption shortens time on the ventilator. Both are standard components of the bundle, not alternatives to each other.'),
(2604, 'CLABSI can present with systemic signs (fever) and/or local signs right at the catheter insertion site (redness/erythema). Either can appear on its own, or both together — that''s why both are things to watch for, not just one.'),
(2608, 'Subglottic suctioning removes secretions that pool just above the ETT cuff before they can leak past it into the lungs, directly cutting VAP risk — that''s a proven part of the VAP-prevention bundle. Routine, scheduled ventilator circuit changes do NOT reduce VAP risk and are no longer recommended practice — circuits should only be changed when visibly soiled or malfunctioning, not on a fixed schedule. That''s why the answer here is subglottic suctioning alone, not "both."'),
(2610, 'Infections caused by multidrug-resistant organisms are harder to treat effectively because fewer antibiotics work against them — this typically means a longer hospital stay to get the infection under control, and a higher risk of the infection proving fatal. Both are well-documented consequences of MDRO infection.'),
(2611, 'Nurses support antibiotic stewardship in two concrete ways: tracking culture and sensitivity results so therapy can be narrowed to the right drug, and making sure prescribed antibiotics are actually administered on time (delayed doses let the infection progress). Both are core nursing responsibilities within stewardship programs.'),
(2612, 'Chlorhexidine skin preparation before line insertion is a proven, evidence-based CLABSI-prevention measure. Routinely changing lines on a fixed 48-hour schedule is NOT recommended — lines should be left in only as long as clinically needed and removed promptly once they''re not, rather than swapped on a timer, since each new insertion is itself a fresh infection risk. That''s why the answer here is chlorhexidine skin prep alone, not "both."'),
(2613, 'CLABSI isn''t caused by just one type of organism — gram-positive organisms like Staphylococcus aureus and gram-negative organisms like Klebsiella pneumoniae are both recognized causes, along with other skin and gut flora that can enter through the line.'),
(2614, 'VAP is diagnosed using a combination of findings rather than one sign alone — a new or worsening infiltrate on chest X-ray together with purulent sputum both support the diagnosis, which is why both are correct here.'),
(2615, 'Infection control programs aim directly at reducing healthcare-associated infections (HAIs), and because HAIs drive up illness severity, death rates, and length of stay, cutting HAIs also improves overall patient outcomes. The two goals are directly linked, not separate.'),
(2616, 'Hand hygiene stops organisms from being carried between patients on staff hands, while isolation precautions (contact precautions, dedicated equipment) stop spread from a colonized or infected patient to others nearby. Both are foundational, complementary measures for controlling MDRO spread — neither alone is enough.'),
(2876, 'Male condoms work as a physical barrier that blocks sperm from reaching the egg (preventing pregnancy) and also blocks the exchange of body fluids that spread sexually transmitted infections. It''s one of the few methods that protects against both at the same time.'),
(2911, 'The fertility awareness method works by tracking more than one sign of ovulation together — changes in cervical mucus consistency (becomes clearer and stretchier near ovulation) and a small rise in basal body temperature after ovulation has occurred. Using both signs together gives a more reliable picture of the fertile window than relying on just one.')
) as v(id, exp)
where q.id = v.id;
