-- CCN Council Prep Pro — OSCE practice questions batch
-- 42 questions tied to the new OSCE/Viva prep section, category='OSCE Practice'.
-- Includes several sourced directly from real JUTH exam papers (marked in the 'source' field)
-- and the Intensive Care Nursing OSCE Exam reference document; the rest are labeled
-- 'AI Practice Question' and grounded in the real procedure checklists supplied.
-- Run this once in the Supabase SQL Editor (Project -> SQL Editor -> New query).

insert into public.questions (id, topic, source, q, opts, ans_idx, exp, category, category_icon, is_active)
values
(3662, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'The following are potential reversible causes of cardiac arrest EXCEPT:', '["Hypoxia", "Hyperlipidaemia", "Hyperkalaemia", "Hypoglycaemia"]'::jsonb, 1, 'The reversible causes of cardiac arrest follow the ''4 Hs and 4 Ts'' (Hypoxia, Hypo/hyperkalaemia, Hypothermia, Hypovolaemia, Tension pneumothorax, Tamponade, Toxins, Thrombosis) — hyperlipidaemia is not among them.', 'OSCE Practice', '🩺', true),
(3663, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'Concerning signs and symptoms of cardiac arrest, which of the following is NOT true?', '["No heart rate", "Electrolytes imbalance", "Patient is cyanosed", "Dilatation of pupils which do not react to light"]'::jsonb, 1, 'Electrolyte imbalance is a cause/contributing factor of cardiac arrest, not itself a sign/symptom of arrest — absent heart rate, cyanosis, and fixed dilated pupils are recognised signs.', 'OSCE Practice', '🩺', true),
(3664, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'Apnoea is a sign of imminent cardiac arrest.', '["Hypotension", "Apnoea", "Absent of major pulses", "Cyanosis"]'::jsonb, 1, 'Apnoea (absence of breathing) is one of the cardinal signs used to recognise imminent/actual cardiac arrest, alongside unresponsiveness and absent major pulses.', 'OSCE Practice', '🩺', true),
(3665, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'When imitating cardiopulmonary resuscitation, if you find a child collapsed and you did not witness it, what do you do?', '["Follow adult resuscitation algorithm", "When you are single, the compression/ventilation ratio should be 15:2", "Do 2 minutes of CPR before calling the emergency room", "Lie the patient in lateral position and do look, listen, feel first before any intervention"]'::jsonb, 2, 'For an unwitnessed paediatric collapse when alone, current guidance is to perform approximately 2 minutes (5 cycles) of CPR before leaving to call for emergency help, since the arrest is often primarily respiratory in origin and may respond to early CPR.', 'OSCE Practice', '🩺', true),
(3666, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'The process of defibrillation and putting a pacemaker into the heart is:', '["Automated defibrillation", "CPR and defibrillation", "Compression and defibrillation", "Cardioversion"]'::jsonb, 3, 'Cardioversion is the umbrella process referring to restoring normal rhythm electrically (with or without an accompanying pacing device) — distinguishing it from plain defibrillation.', 'OSCE Practice', '🩺', true),
(3667, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'CPR resuscitation is counterproductive in:', '["Cardiac arrest", "Shock", "Upper airway region obstruction only, with no cardiac component", "None of the above"]'::jsonb, 2, 'CPR targets the absence of effective circulation/breathing from cardiac arrest — it is not the appropriate primary treatment for a simple isolated upper airway obstruction with an otherwise beating heart (airway clearance manoeuvres are indicated instead).', 'OSCE Practice', '🩺', true),
(3668, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'Cardiac arrest is defined as:', '["Sudden collapse of a patient who is not supposed to die", "Loss of consciousness with absence of circulation accompanied by absent or gasping respiration", "Sudden cessation of femoral pulse alone", "Sudden cessation of pulse rate temporarily"]'::jsonb, 1, 'Cardiac arrest is clinically defined by loss of consciousness with absent circulation, accompanied by absent breathing or agonal gasping — not merely a subjective sense that a death was unexpected.', 'OSCE Practice', '🩺', true),
(3669, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', 'All are causes of cardiac arrest EXCEPT:', '["Cardiac disease", "Circulatory causes", "Metabolic changes", "Asystole"]'::jsonb, 3, 'Asystole is itself a cardiac arrest rhythm (the outcome), not a cause of arrest — cardiac disease, circulatory causes, and metabolic changes are recognised underlying causes.', 'OSCE Practice', '🩺', true),
(3670, 'OSCE: BLS / CPR', 'JUTH Post Basic Critical Care Nursing Programme — MCQ on CPR (14 Aug 2024)', '__________ is a cardinal sign of cardiac arrest.', '["Tachycardia", "Dyspnoea/Tachypnoea", "Cyanosis", "Severe chest pain"]'::jsonb, 2, 'Cyanosis is one of the classic cardinal signs assessed alongside unresponsiveness, apnoea, and absent pulses when recognising cardiac arrest.', 'OSCE Practice', '🩺', true),
(3671, 'OSCE: BLS / CPR', 'AI Practice Question', 'During the OSCE assessment of BLS, the candidate is expected to check for responsiveness AND circulation/breathing within approximately how long?', '["30 seconds", "10 seconds", "2 minutes", "No time limit is assessed"]'::jsonb, 1, 'The initial responsiveness and breathing/circulation check should be completed within about 10 seconds — prolonged assessment delays the start of compressions.', 'OSCE Practice', '🩺', true),
(3672, 'OSCE: BLS / CPR', 'AI Practice Question', 'On the JUTH BLS OSCE checklist, correct chest compression depth for an adult is assessed as:', '["1–2cm", "5–6cm (2–3 inches)", "10cm", "No specific depth is checked"]'::jsonb, 1, 'The checklist specifically marks compression depth of about 5–6cm (2–3 inches), matching international BLS guidelines.', 'OSCE Practice', '🩺', true),
(3673, 'OSCE: BLS / CPR', 'AI Practice Question', 'In the OSCE BLS checklist, AED pad application and shock delivery is worth how many of the 20 total marks?', '["0.5", "1", "2", "5"]'::jsonb, 2, 'AED use — turning it on, following prompts, applying pads correctly, and delivering a shock if indicated — is weighted at 2 marks on the checklist, reflecting its clinical importance.', 'OSCE Practice', '🩺', true),
(3674, 'OSCE: Central Line', 'Intensive Care Nursing OSCE Exam', 'Which of the following is considered an absolute contraindication for obtaining arterial blood gases (ABG)?', '["Anti-coagulation therapy", "Liver disease", "Arteriovenous fistula at the intended puncture site", "Low platelet count"]'::jsonb, 2, 'An arteriovenous fistula (e.g. for dialysis) at the intended site is an absolute contraindication for arterial puncture there, since disrupting it risks serious complications — the other options are relative contraindications requiring caution, not absolute prohibition.', 'OSCE Practice', '🩺', true),
(3675, 'OSCE: Central Line', 'Intensive Care Nursing OSCE Exam', 'The Modified Allen''s Test involves assessment of:', '["Nerve supply", "Venous supply", "Arterial supply", "Peripheral movement"]'::jsonb, 2, 'The Modified Allen''s Test assesses collateral arterial supply (via the ulnar artery) to the hand before radial artery puncture.', 'OSCE Practice', '🩺', true),
(3676, 'OSCE: Central Line', 'Intensive Care Nursing OSCE Exam', 'Accurate measurement of central venous pressure requires the transducer to be levelled at:', '["Mid-axillary line, 4th intercostal space", "Mid-clavicular line, 4th intercostal space", "Mid-axillary line, 5th intercostal space", "Mid-clavicular line, 5th intercostal space"]'::jsonb, 0, 'The phlebostatic axis — mid-axillary line at the 4th intercostal space — is the standard reference point for levelling a CVP transducer.', 'OSCE Practice', '🩺', true),
(3677, 'OSCE: Central Line', 'Intensive Care Nursing OSCE Exam', 'Which of the following central venous pressure readings suggests a condition of hypervolaemia?', '["5 H2O", "6mmHg", "13 H2O", "2mmHg"]'::jsonb, 2, 'A CVP of 13cmH2O is above the normal range (roughly 2–8mmHg, or a slightly higher range when measured in cmH2O), suggesting hypervolaemia/fluid overload.', 'OSCE Practice', '🩺', true),
(3678, 'OSCE: Central Line', 'AI Practice Question', 'On the Central Line Procedure checklist, obtaining informed consent and patient identification is worth how many marks out of the insertion section''s total of 5?', '["0", "0.5", "1", "2"]'::jsonb, 2, 'Patient identification and informed consent is allocated 1 of the 5 marks for the insertion section — a required first step before any invasive procedure begins.', 'OSCE Practice', '🩺', true),
(3679, 'OSCE: Central Line', 'AI Practice Question', 'According to the Central Line Care checklist, ''scrub-the-hub'' technique is specifically part of which section?', '["Central Line Insertion", "Blood Sampling from Central Line", "Prevention of infection and complications (Central Line Care)", "Not part of any section"]'::jsonb, 2, '''Scrub-the-hub'' before every line access is listed under the Central Line Care section''s infection/complication prevention item.', 'OSCE Practice', '🩺', true),
(3680, 'OSCE: ETT Suctioning', 'Intensive Care Nursing OSCE Exam', 'Which of the following statements describes sterile nursing practice when suctioning an endotracheal tube?', '["Hyperoxygenation before each cycle of suctioning", "Use a separate suction catheter for ETT suctioning for 48 hours", "Suctioning the patient every 2 hours regardless of need", "Use a separate tube and washing solution for ETT suctioning"]'::jsonb, 3, 'Using a separate, dedicated catheter and washing solution specifically for ETT suctioning (distinct from oral suctioning equipment) maintains sterility of the lower airway suctioning technique.', 'OSCE Practice', '🩺', true),
(3681, 'OSCE: ETT Suctioning', 'Intensive Care Nursing OSCE Exam', 'True or False: The mechanically ventilated patient should resume a high Fowler''s position to allow proper functioning of the machine.', '["True", "False", "Only for paediatric patients", "Only during suctioning"]'::jsonb, 1, 'This is FALSE — ventilated patients are generally positioned with the head of bed elevated 30–45 degrees (semi-Fowler''s), not full high Fowler''s, balancing ventilator function, VAP prevention, and comfort.', 'OSCE Practice', '🩺', true),
(3682, 'OSCE: ETT Suctioning', 'Intensive Care Nursing OSCE Exam', 'True or False: A mal-connected circuit may initiate a high alarm pressure on the mechanical ventilator.', '["True", "False", "Only affects low-pressure alarms", "Only relevant during weaning"]'::jsonb, 1, 'This is FALSE — a mal-connected (disconnected/leaking) circuit typically triggers a LOW pressure alarm, not high pressure, since the set pressure/volume cannot be achieved through the leak.', 'OSCE Practice', '🩺', true),
(3683, 'OSCE: ETT Suctioning', 'Intensive Care Nursing OSCE Exam', 'True or False: An oral airway should be inserted routinely for every patient with a mechanical ventilator.', '["True", "False", "Only for tracheostomy patients", "Only for paediatric patients"]'::jsonb, 1, 'This is FALSE — an oral airway (OPA) is not routine for all ventilated patients; most ventilated patients are already intubated via ETT, and an OPA is used selectively (e.g. to prevent biting an oral ETT) rather than as a blanket routine.', 'OSCE Practice', '🩺', true),
(3684, 'OSCE: ETT Suctioning', 'Intensive Care Nursing OSCE Exam', 'True or False: CPAP mode helps the patient in the process of weaning.', '["True", "False", "Only in paediatric patients", "Only for tracheostomy patients"]'::jsonb, 0, 'This is TRUE — CPAP (Continuous Positive Airway Pressure) is commonly used as a weaning mode, allowing the patient to breathe spontaneously with pressure support as ventilator dependence is gradually reduced.', 'OSCE Practice', '🩺', true),
(3685, 'OSCE: ETT Suctioning', 'AI Practice Question', 'On the Care of the Endotracheal Tube checklist, checking the safety (pilot) balloon is assessed under which category?', '["Introduction", "Confirming the cuff is intact, part of the main procedure", "Conclusion", "Not part of the checklist"]'::jsonb, 1, 'Checking the pilot balloon to confirm cuff integrity is one of the core procedure-section items on the ETT care checklist.', 'OSCE Practice', '🩺', true),
(3686, 'OSCE: Tracheostomy Care', 'AI Practice Question', 'On the Tracheostomy Tube care checklist, why is a spare tube kept at the bedside?', '["It is not required by the checklist", "In case of accidental decannulation, especially important before the stoma tract has matured", "Only needed for paediatric patients", "Only needed if the patient develops a fever"]'::jsonb, 1, 'A spare tracheostomy tube (same size and one size smaller) at the bedside allows prompt reinsertion if the tube is accidentally dislodged, particularly critical in the first 7–10 days before the tract matures.', 'OSCE Practice', '🩺', true),
(3687, 'OSCE: Tracheostomy Care', 'AI Practice Question', 'According to the Tracheostomy Tube checklist, assessing the stoma for signs of infection is part of:', '["The Introduction section", "The Procedure section", "The Conclusion section", "Not included on the checklist"]'::jsonb, 1, 'Stoma assessment for healing/signs of infection is one of the core procedure-section items on the tracheostomy care checklist.', 'OSCE Practice', '🩺', true),
(3688, 'OSCE: OPA & Suctioning', 'AI Practice Question', 'On the OPA Insertion and Suctioning checklist, how long should each suction pass last before removing the catheter?', '["1 minute", "10–15 seconds", "5 minutes", "No time limit"]'::jsonb, 1, 'The checklist specifies suctioning for 10–15 seconds before removing the catheter, consistent with standard practice to avoid prolonged hypoxia.', 'OSCE Practice', '🩺', true),
(3689, 'OSCE: OPA & Suctioning', 'AI Practice Question', 'On the OPA Insertion and Suctioning checklist, how long should the nurse wait before suctioning again if further secretions remain?', '["No waiting is required", "About 1 minute", "10 minutes", "1 hour"]'::jsonb, 1, 'The checklist specifies waiting about 1 minute between suction passes, allowing the patient''s oxygen saturation to recover before the next attempt.', 'OSCE Practice', '🩺', true),
(3690, 'OSCE: OPA & Suctioning', 'AI Practice Question', 'According to the checklist, which suctioning device is specified for OPA-assisted oropharyngeal suctioning?', '["A soft flexible catheter only", "Yankauer catheter", "A nasogastric tube", "No specific device is specified"]'::jsonb, 1, 'The checklist specifies choosing the correct suctioning device — the rigid Yankauer catheter — for oropharyngeal suctioning.', 'OSCE Practice', '🩺', true),
(3691, 'OSCE: Syringe Pump', 'AI Practice Question', 'On the Syringe Pump checklist, the ''5 Rights of Drug Administration'' are used to verify the patient''s identity together with which other checks?', '["Drug, route, dosage, and time", "Only the drug name", "Only the dosage", "No other checks are required"]'::jsonb, 0, 'The 5 Rights framework verifies right patient, right drug, right route, right dosage and right time — all checked together, not the patient identity alone.', 'OSCE Practice', '🩺', true),
(3692, 'OSCE: Syringe Pump', 'AI Practice Question', 'According to the checklist, why must air bubbles be removed from the syringe before starting the infusion?', '["It has no clinical importance", "To prevent inaccurate dosing at the start of the infusion and reduce embolism risk", "To make the syringe pump alarm sound", "To speed up the infusion rate"]'::jsonb, 1, 'Air in the syringe/line can cause inaccurate initial dosing and, particularly with central access, carries a small air embolism risk.', 'OSCE Practice', '🩺', true),
(3693, 'OSCE: Endotracheal Intubation', 'AI Practice Question', 'On the Endotracheal Intubation checklist, what position is the patient placed in before laryngoscopy?', '["Flat, no positioning needed", "Sniffing position — pillow behind the neck, neck flexed", "Trendelenburg position", "Prone position"]'::jsonb, 1, 'The checklist specifies the sniffing position, aligning the oral, pharyngeal and laryngeal axes for the best possible glottic view.', 'OSCE Practice', '🩺', true),
(3694, 'OSCE: Endotracheal Intubation', 'AI Practice Question', 'According to the checklist, which hand holds the laryngoscope, and from which side is it inserted into the mouth?', '["Right hand; inserted from the left", "Left hand; inserted from the right, sweeping the tongue to the left", "Either hand; inserted from the centre", "Left hand; inserted from the left"]'::jsonb, 1, 'The checklist specifies grabbing the laryngoscope with the non-dominant (conventionally left) hand and inserting from the right side of the mouth, sweeping the tongue leftward.', 'OSCE Practice', '🩺', true),
(3695, 'OSCE: Endotracheal Intubation', 'AI Practice Question', 'On the checklist, how is correct ETT placement confirmed after insertion?', '["By verbal report from the patient", "Using an Ambu bag to check for chest rise/fall and auscultation, connecting to an O2 source", "No confirmation step is listed", "By checking the patient''s blood pressure only"]'::jsonb, 1, 'The final checklist item specifies confirming placement via chest rise/fall with bagging and auscultation, then connecting to the oxygen source.', 'OSCE Practice', '🩺', true),
(3696, 'OSCE: Oxygen Therapy', 'AI Practice Question', 'According to the Oxygen Therapy marking criteria, before applying the mask the nurse should ensure the reservoir bag is:', '["Left flat/empty", "Fully inflated by covering the one-way valve with fingers first", "Removed entirely", "Filled with water"]'::jsonb, 1, 'For a non-rebreather mask, the reservoir bag must be pre-filled (by occluding the valve) before application, so the patient receives a high FiO2 from the first breath.', 'OSCE Practice', '🩺', true),
(3697, 'OSCE: Oxygen Therapy', 'AI Practice Question', 'On the Oxygen Therapy checklist, which body areas should be regularly inspected for pressure injury during oxygen mask use?', '["Only the hands", "Face, ears, and back of the head", "Only the feet", "No specific areas are checked"]'::jsonb, 1, 'The checklist specifically requires inspection of the face, ears and back of the head, since mask straps and tubing can cause pressure injury with prolonged use.', 'OSCE Practice', '🩺', true),
(3698, 'OSCE: Pain Assessment', 'AI Practice Question', 'In the PQRST pain assessment framework used on the checklist, what does the ''S'' stand for?', '["Site", "Severity, assessed using a universal pain scale", "Sensation", "Speed of onset"]'::jsonb, 1, 'In PQRST, S stands for Severity — assessed using a standardised pain scale to allow objective tracking over time.', 'OSCE Practice', '🩺', true),
(3699, 'OSCE: Pain Assessment', 'AI Practice Question', 'What does the ''R'' in the PQRST pain assessment framework assess?', '["Rate of the pulse", "Radiation — whether the pain moves or started elsewhere", "Respiratory rate", "Range of motion"]'::jsonb, 1, '''R'' stands for Radiating — assessing whether the pain is localised, moves, or radiates elsewhere, which carries diagnostic significance (e.g. cardiac pain radiating to the arm/jaw).', 'OSCE Practice', '🩺', true),
(3700, 'OSCE: PEFR', 'AI Practice Question', 'On the PEFR checklist, how many attempts should be performed, and how is the final result recorded?', '["One attempt only", "Three attempts, recording the best of the three", "Five attempts, recording the average", "Two attempts, recording the lowest"]'::jsonb, 1, 'The checklist specifies performing three attempts and documenting the best (highest) of the three acceptable readings.', 'OSCE Practice', '🩺', true),
(3701, 'OSCE: PEFR', 'AI Practice Question', 'On the PEFR checklist, what type of expiratory effort should the patient be instructed to perform?', '["A slow, sustained blow lasting 10 seconds", "A short, sharp forceful ''huff''", "Gentle, quiet breathing", "Holding their breath"]'::jsonb, 1, 'PEFR measures the peak (maximum instantaneous) flow rate, requiring a short, sharp, maximally forceful expiratory effort — not a slow sustained blow.', 'OSCE Practice', '🩺', true),
(3702, 'OSCE: Pressure Ulcer Prevention', 'AI Practice Question', 'According to the marking criteria, a specific foam preventative dressing applied to the sacrum has been shown to reduce pressure ulcer development by approximately:', '["No measurable effect", "10%", "90%", "100%, eliminating all risk"]'::jsonb, 1, 'The marking criteria states the foam dressing reduces pressure ulcer development by around 10% — a meaningful but partial risk reduction, not a guarantee.', 'OSCE Practice', '🩺', true),
(3703, 'OSCE: Pressure Ulcer Prevention', 'AI Practice Question', 'Besides a preventative dressing, which other measures does the checklist specify for pressure ulcer prevention?', '["Strict bed rest with no repositioning", "Regular skin inspection, repositioning, staying well hydrated, and balanced diet", "Avoiding all fluid intake", "Only medication, with no positional care"]'::jsonb, 1, 'The checklist emphasises a multi-factorial approach: regular skin inspection, repositioning, hydration and nutrition all work together for pressure ulcer prevention.', 'OSCE Practice', '🩺', true)
on conflict (id) do update set topic=excluded.topic, source=excluded.source, q=excluded.q, opts=excluded.opts, ans_idx=excluded.ans_idx, exp=excluded.exp, category=excluded.category, category_icon=excluded.category_icon, is_active=true;